package com.tfg.ws.rest.TFGREST.objetos;
// Generated 7 oct. 2020 18:24:47 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Agentes generated by hbm2java
 */

@Entity
@Table(name = "Agentes")
public class Agentes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "contra", unique = true, nullable = false)
	private String contra;

	@Column(name = "dni", unique = true)
	private String dni;
	
	@Column(name = "nombre")
	private String nombre;

	@Column(name = "usu", unique = true)
	private String usu;

	@Column(name = "hospital", nullable = true)
	private String hospital;

	@Column(name = "depart", nullable = true)
	private String depart;

	@Column(name = "codigo", unique = true, nullable = false)
	private String codigo;

	@OneToMany(mappedBy = "agentes")
	private Set<Consentimientos> consentimientoses = new HashSet<Consentimientos>(0);

	public Agentes() {
	}

	public Agentes(String contra, String hospital, String depart, String codigo) {
		this.contra = contra;
		this.hospital = hospital;
		this.depart = depart;
		this.codigo = codigo;
	}

	public Agentes(String contra, String dni, String nombre, String usu, String codigo,
			Set<Consentimientos> consentimientoses) {
		this.contra = contra;
		this.dni = dni;
		this.nombre = nombre;
		this.usu = usu;
		this.codigo = codigo;
		this.consentimientoses = consentimientoses;
	}
	
	public Agentes(String contra, String dni, String nombre, String usu, String hospital, String depart, String codigo,
			Set<Consentimientos> consentimientoses) {
		this.contra = contra;
		this.dni = dni;
		this.nombre = nombre;
		this.usu = usu;
		this.hospital = hospital;
		this.depart = depart;
		this.codigo = codigo;
		this.consentimientoses = consentimientoses;
	}

	public String getContra() {
		return this.contra;
	}

	public void setContra(String contra) {
		this.contra = contra;
	}

	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}
	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsu() {
		return this.usu;
	}

	public void setUsu(String usu) {
		this.usu = usu;
	}

	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	public String getDepart() {
		return this.depart;
	}

	public void setDepart(String depart) {
		this.depart = depart;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@JsonManagedReference
	public Set<Consentimientos> getConsentimientoses() {
		return this.consentimientoses;
	}

	public void setConsentimientoses(Set<Consentimientos> consentimientoses) {
		this.consentimientoses = consentimientoses;
	}

}
